# Generated by Django 2.0.9 on 2018-11-21 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('timeslot', models.CharField(choices=[('MO', 'Moring'), ('AF', 'Afternoon'), ('EV', 'Evening'), ('NI', 'Night')], default='MO', max_length=2)),
                ('published', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(to='todolist.Member')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
